version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  tenant-service:
    build:
      context: .
      dockerfile: ./src/Services/TenantService/TenantService.API/Dockerfile
    container_name: tenant-service
    ports:
      - "5001:5001"
    environment:
      - CONSUL_ADDRESS=http://consul:8500
      - SERVICE_NAME=TenantService
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=TenantDB;Username=postgres;Password=E18080561
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://tenant-service:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  analytics-service:
    build:
      context: .
      dockerfile: ./src/Services/AnalyticsService/AnalyticsService.API/Dockerfile
    container_name: analytics-service
    ports:
      - "5003:5003"
    environment:
      - CONSUL_ADDRESS=http://consul:8500
    networks:
      - my_network

  api-gateway:
    build:
      context: .
      dockerfile: ./ApiGateway/Dockerfile
    container_name: api-gateway
    ports:
      - "5020:5000"
    depends_on:
      - tenant-service
      - analytics-service
    environment:
      - CONSUL_ADDRESS=http://consul:8500
    networks:
      - my_network
    labels:
      - "consul.service.name=api-gateway"
