// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantService.Infrastructure.Persistence.Context;

#nullable disable

namespace TenantService.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20241113061905_Tenat_v1")]
    partial class Tenat_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantService.Domain.Entities.AddOn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("AddOns", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340),
                            Description = "Agrega más usuarios al sistema",
                            Identifier = "EXTRA_USER",
                            IsActive = true,
                            Name = "Usuarios Adicionales",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340),
                            Description = "Agrega más sucursales al sistema",
                            Identifier = "EXTRA_BRANCH",
                            IsActive = true,
                            Name = "Sucursales Adicionales",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340),
                            Description = "Agrega más almacenamiento al sistema",
                            Identifier = "EXTRA_STORAGE",
                            IsActive = true,
                            Name = "Almacenamiento Adicional",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(6340)
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.AddOnFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddOnId")
                        .HasColumnType("integer")
                        .HasColumnName("add_on_id");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_id");

                    b.Property<int?>("IncrementValue")
                        .HasColumnType("integer")
                        .HasColumnName("increment_value");

                    b.HasKey("Id");

                    b.HasIndex("AddOnId");

                    b.ToTable("AddOnFeatures", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddOnId = 1,
                            FeatureId = 1,
                            IncrementValue = 1
                        },
                        new
                        {
                            Id = 2,
                            AddOnId = 1,
                            FeatureId = 2,
                            IncrementValue = 1
                        },
                        new
                        {
                            Id = 3,
                            AddOnId = 2,
                            FeatureId = 1,
                            IncrementValue = 1
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Features", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(9990),
                            Description = "Número máximo de usuarios que pueden acceder al sistema",
                            Identifier = "USERS",
                            Name = "Usuarios",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 258, DateTimeKind.Utc).AddTicks(9990)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc),
                            Description = "Espacio de almacenamiento en disco",
                            Identifier = "STORAGE",
                            Name = "Almacenamiento",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc),
                            Description = "Soporte técnico",
                            Identifier = "SUPPORT",
                            Name = "Soporte",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc),
                            Description = "Número máximo de sucursales que pueden gestionar",
                            Identifier = "BRANCHES",
                            Name = "Sucursales",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean")
                        .HasColumnName("is_custom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("Plans", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Plan básico",
                            Identifier = "BASIC",
                            IsActive = true,
                            IsCustom = false,
                            Name = "Básico",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Plan estándar",
                            Identifier = "STANDARD",
                            IsActive = true,
                            IsCustom = false,
                            Name = "Estándar",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Plan premium",
                            Identifier = "PREMIUM",
                            IsActive = true,
                            IsCustom = false,
                            Name = "Premium",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300),
                            Description = "Plan personalizado",
                            Identifier = "CUSTOM",
                            IsActive = true,
                            IsCustom = true,
                            Name = "Personalizado",
                            UpdatedAt = new DateTime(2024, 11, 13, 6, 19, 5, 259, DateTimeKind.Utc).AddTicks(1300)
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer")
                        .HasColumnName("feature_id");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlimited");

                    b.Property<int?>("LimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("limit_value");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanFeatures", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeatureId = 1,
                            IsUnlimited = false,
                            LimitValue = 5,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            FeatureId = 2,
                            IsUnlimited = false,
                            LimitValue = 500,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            FeatureId = 3,
                            IsUnlimited = false,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 4,
                            FeatureId = 4,
                            IsUnlimited = false,
                            LimitValue = 2,
                            PlanId = 1
                        },
                        new
                        {
                            Id = 5,
                            FeatureId = 1,
                            IsUnlimited = false,
                            LimitValue = 10,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 6,
                            FeatureId = 2,
                            IsUnlimited = false,
                            LimitValue = 1000,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 7,
                            FeatureId = 3,
                            IsUnlimited = false,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 8,
                            FeatureId = 4,
                            IsUnlimited = false,
                            LimitValue = 5,
                            PlanId = 2
                        },
                        new
                        {
                            Id = 9,
                            FeatureId = 1,
                            IsUnlimited = false,
                            LimitValue = 20,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 10,
                            FeatureId = 2,
                            IsUnlimited = true,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 11,
                            FeatureId = 3,
                            IsUnlimited = true,
                            PlanId = 3
                        },
                        new
                        {
                            Id = 12,
                            FeatureId = 4,
                            IsUnlimited = true,
                            PlanId = 3
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Pricing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percentage");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interval");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("Pricings", "tenant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 1,
                            EntityType = "Plan",
                            Interval = "monthly",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 2,
                            EntityType = "Plan",
                            Interval = "monthly",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 3,
                            EntityType = "Plan",
                            Interval = "monthly",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 4,
                            EntityType = "Plan",
                            Interval = "monthly",
                            Price = 400m
                        },
                        new
                        {
                            Id = 5,
                            Currency = "MXM",
                            DiscountPercentage = 10,
                            EntityId = 1,
                            EntityType = "Plan",
                            Interval = "yearly",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 6,
                            Currency = "MXM",
                            DiscountPercentage = 10,
                            EntityId = 2,
                            EntityType = "Plan",
                            Interval = "yearly",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 7,
                            Currency = "MXM",
                            DiscountPercentage = 10,
                            EntityId = 3,
                            EntityType = "Plan",
                            Interval = "yearly",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 8,
                            Currency = "MXM",
                            DiscountPercentage = 10,
                            EntityId = 4,
                            EntityType = "Plan",
                            Interval = "yearly",
                            Price = 4000m
                        },
                        new
                        {
                            Id = 9,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 1,
                            EntityType = "AddOn",
                            Interval = "monthly",
                            Price = 10m
                        },
                        new
                        {
                            Id = 10,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 2,
                            EntityType = "AddOn",
                            Interval = "monthly",
                            Price = 20m
                        },
                        new
                        {
                            Id = 11,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 3,
                            EntityType = "AddOn",
                            Interval = "monthly",
                            Price = 30m
                        },
                        new
                        {
                            Id = 12,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 1,
                            EntityType = "AddOn",
                            Interval = "yearly",
                            Price = 100m
                        },
                        new
                        {
                            Id = 13,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 2,
                            EntityType = "AddOn",
                            Interval = "yearly",
                            Price = 200m
                        },
                        new
                        {
                            Id = 14,
                            Currency = "MXM",
                            DiscountPercentage = 0,
                            EntityId = 3,
                            EntityType = "AddOn",
                            Interval = "yearly",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseConnectionString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_connection_string");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.HasKey("Id");

                    b.ToTable("Tenants", "tenant");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renewal");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("interval");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantsSubscriptions", "billing", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TenantService.Domain.Entities.AddOnFeature", b =>
                {
                    b.HasOne("TenantService.Domain.Entities.AddOn", "AddOn")
                        .WithMany("AddOnFeatures")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantService.Domain.Entities.Feature", "Feature")
                        .WithMany("AddOnFeatures")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("TenantService.Domain.Entities.Feature", "Feature")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantService.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanFeatures")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("TenantService.Domain.Entities.Plan", "Plan")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantService.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.AddOn", b =>
                {
                    b.Navigation("AddOnFeatures");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Feature", b =>
                {
                    b.Navigation("AddOnFeatures");

                    b.Navigation("PlanFeatures");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanFeatures");

                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("TenantService.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
